### PR TITLE
36 implement metrics frontend

### PR DESCRIPTION
**Pull request by Marsellus19**
For the time being, the ui is basic. I will spice things up later.

### CODE REVIEW

**Comment by amrukwa** [comment]
The pylint problems are on my side and are resolved on another branch. I'm looking into the rest right now.

**Comment by Marsellus19** [comment]
If by tests you mean an exemplary usage, no I do not have anything of particular note written. Although I've prepared a dpg group for the metrics inside the App class. Calling draw inside that group will place the metric values side by side, below the axis. So I has to look like something in the lines of::
```
f_measure = Value("F measure")
precision = Value("Precision")

with dpg.group(horizontal=True):
                f_measure.draw()
                precision.draw()
```

Which will result in this:

image


I've additionally followed the convention of class usage found in other places in the code. So it is necessary to call draw() first to add an element onto the screen. Then after changing the value using set_value, update() has to be called to refresh the ui. I also added a possibility to replace the numerical value with an error message. Which is a feature I believe You requested.

**Comment by Marsellus19** [comment]
One additional thing of note. I can see that the render loop has been moved away from the App class into check_interactions in Axis. It will be necessary to move it back in order to allow elements other than axis be updated. That also accounts for the metrics. I will create a new issue for that. I believe it also makes sense from the architecture point of view. The main loop should not be tucked away inside a small class representing a portion of the ui.

**Comment by amrukwa** [comment]
i think that this form of updating you proposed is good and will be quite convenient. I may have some additional questions at the point of merging the layers of the application, but for now i think it's good.

**Review by amrukwa — APPROVED** [review]

**Comment by Marsellus19** [comment]
Okay, thanks. I will improve the looks of the metrics meanwhile.

**Pull request merged**
